spring.application.name=cadifyWAS

# postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cadify
spring.datasource.username=jaekwan
spring.datasource.password=aries
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Token
jwt.secret=7DPk/entPDK=J19276EITN+=d3KJ/sadAOIjdk234SD18+/tdklKDT254
jwt.expiration=5000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs